"""Method A driver — train FC emulator + amortized corr/rmse fitter on real data.

Stage 1: fit PCA-256 (whiten) on simulated FC, train FCEmulator E: theta->feat.
Stage 2: load empirical FCs, train AmortizedFitNet Q: empFC feat -> theta with
         L = (1-corr) + lambda*rmse in FC space (grad through frozen E + PCA).

Inputs (real, GPU-generated by main_HCP.py):
  output_hcp/features_stage1.npz   'theta_scaled' (N,12), 'fc_raw' (N,64620)
  HCP_Data/HCP_FC.mat  'C'         empirical 381x381 FC (sliced to 360 cortical)
  HCP_Data/HCP_CABNP381_SC_first100.mat  'sub_num'  subject ids to fit

Outputs:
  output_hcp/emulator_fit.pt       emulator + fitnet weights, PCA buffers
  output_hcp/fit_theta_pred.npy    predicted theta_scaled per empirical subject
                                   (feed to cuBNM resim for TRUE FC-corr check)

NOTE: training corr/rmse are EMULATED (surrogate). The honest validation is to
resim fit_theta_pred.npy with the real cuBNM engine and recompute FC corr — the
emulator can only be trusted up to its own MSE + the sim->real OOD gap.
"""
import argparse
import os
import numpy as np
import scipy.io as sio
import torch

from inference.emulator import (
    PCAProjector, FCEmulator, AmortizedFitNet,
    train_emulator, train_amortized_fit, fc_corr_rmse_loss,
)

N_CORT = 360


def load_sim_pairs(path):
    d = np.load(path)
    theta = d["theta_scaled"].astype(np.float32)
    fc = d["fc_raw"].astype(np.float32)
    fc = np.nan_to_num(fc, nan=0.0, posinf=0.0, neginf=0.0)
    print(f"[data] sim pairs: theta {theta.shape}  fc {fc.shape}")
    return theta, fc


def load_empirical_fc(fc_path, sc_path):
    """Empirical FC upper-tri (M,64620) for CABNP sub_num subjects, same 360
    cortical upper-tri convention as the pipeline (triu k=1)."""
    sub_num = np.asarray(sio.loadmat(sc_path)["sub_num"]).ravel().astype(int)
    C = sio.loadmat(fc_path)["C"]
    idx = {int(np.asarray(C[r, 0]).ravel()[0]): r for r in range(C.shape[0])}
    iu = np.triu_indices(N_CORT, k=1)
    rows, ids = [], []
    for sid in sub_num:
        if sid not in idx:
            continue
        fc = np.asarray(C[idx[sid], 1], dtype=np.float32)[:N_CORT, :N_CORT]
        fc = np.nan_to_num(fc, nan=0.0, posinf=0.0, neginf=0.0)
        rows.append(fc[iu]); ids.append(sid)
    emp = np.stack(rows, 0).astype(np.float32)
    print(f"[data] empirical FC: {emp.shape} for {len(ids)} subjects")
    return emp, np.array(ids)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--features", default="output_hcp/features_stage1.npz")
    ap.add_argument("--fc", default="HCP_Data/HCP_FC.mat")
    ap.add_argument("--sc", default="HCP_Data/HCP_CABNP381_SC_first100.mat")
    ap.add_argument("--out", default="output_hcp/emulator_fit.pt")
    ap.add_argument("--theta_out", default="output_hcp/fit_theta_pred.npy")
    ap.add_argument("--pca_dim", type=int, default=256)
    ap.add_argument("--lam", type=float, default=0.5, help="rmse weight in loss")
    ap.add_argument("--emu_epochs", type=int, default=200)
    ap.add_argument("--fit_epochs", type=int, default=400)
    ap.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    args = ap.parse_args()
    print(f"[cfg] device={args.device} pca_dim={args.pca_dim} lam={args.lam}")

    # ---- Stage 1: PCA + emulator on simulated pairs ------------------------
    theta, fc = load_sim_pairs(args.features)
    pca, skp = PCAProjector.fit(fc, n_components=args.pca_dim, whiten=True)
    feat = skp.transform(fc).astype(np.float32)
    ev = float(skp.explained_variance_ratio_.sum())
    print(f"[pca] {args.pca_dim} comps, explained var {ev:.3f}")

    emu = FCEmulator(theta_dim=theta.shape[1], feat_dim=args.pca_dim)
    emu, eh = train_emulator(emu, torch.tensor(theta), torch.tensor(feat),
                             epochs=args.emu_epochs, batch=1024,
                             device=args.device)
    print(f"[emu] best val_mse {min(eh):.5f}")

    # ---- Stage 2: amortized fit on empirical FCs ---------------------------
    emp, emp_ids = load_empirical_fc(args.fc, args.sc)
    pca = pca.to(args.device)
    with torch.no_grad():
        emp_feat = pca.encode(torch.tensor(emp, device=args.device))

    net = AmortizedFitNet(feat_dim=args.pca_dim, theta_dim=theta.shape[1])
    net, fh = train_amortized_fit(net, emu, pca, emp_feat, lam=args.lam,
                                  epochs=args.fit_epochs, batch=64,
                                  device=args.device)
    print(f"[fit] final EMULATED corr {fh[-1]['corr']:.4f}  rmse {fh[-1]['rmse']:.4f}")

    # ---- predict theta per empirical subject + save ------------------------
    net.eval()
    with torch.no_grad():
        theta_pred = net(emp_feat).cpu().numpy().astype(np.float32)
    os.makedirs(os.path.dirname(args.theta_out) or ".", exist_ok=True)
    np.save(args.theta_out, theta_pred)
    torch.save({"emulator": emu.state_dict(), "fitnet": net.state_dict(),
                "pca_components": skp.components_, "pca_mean": skp.mean_,
                "pca_ev": skp.explained_variance_, "emp_ids": emp_ids,
                "lam": args.lam, "emu_val_mse": min(eh),
                "fit_hist": fh}, args.out)
    print(f"[save] {args.out}  |  {args.theta_out} {theta_pred.shape}")
    print("[next] resim fit_theta_pred.npy with cuBNM (engine_select) to get "
          "the TRUE FC corr — emulated corr is a surrogate upper-estimate.")


if __name__ == "__main__":
    main()
